#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request 
#	- (requesting a page) using curl, it must return a page
#	- that contains the string Hello World!


# Install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Set the listening port to 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a default index.html file
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
