#!/usr/bin/env bash

# Update the package list and install Nginx
# Create a configuration file for the redirection

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
str="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "s|server_name\ _;|$str|" /etc/nginx/sites-available/default
service nginx restart
