#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a configuration file for the redirection
echo 'server {
	listen 80;
	server_name 52.3.254.195;
	
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
}' | sudo tee /etc/nginx/sites-available/redirect_me

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo nginx -t
sudo systemctl reload nginx
