#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
str="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s|server_name _;|$str/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|listen 80 default_server;|$str|" /etc/nginx/sites-enabled/default
sudo service nginx restart
