#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt upgrade

sudo apt install haproxy

global
  log 127.0.0.1 local2
  maxconn 4096

defaults
  log global
  mode http
  option httplog
  option dontlognull
  retries 3
  timeout connect 5s
  timeout client 10s
  timeout server 10s

frontend http
  bind :80
  default_backend webservers

backend webservers
  balance roundrobin
  server web01 52.3.254.195:80 check
  server web02 54.197.42.179:80 check

sudo systemctl enable haproxy
sudo systemctl start haproxy
