#!/usr/bin/env bash
# Use awk to group visitors by IP and HTTP status code
# Count occurrences
# Sort the data

awk '{count[$1" "$9]++} END {for (data in count) print count[data], data}' apache-access.log | sort -nr
