#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
# displays hours from 0 to 12
# displays minutes from 1 to 59

hour=0

while [ $hour -lt 12 ]; do
    echo "Hour: $hour"

    minute=1
    while [ $minute -lt 60 ]; do
        echo "$minute"
        (( minute += 1 ))
    done
    (( hour += 1 ))
done
