#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed 

current_dir=$("ls")

for i in $current_dir
do
    echo "$i" | cut -d '-' -f2
done
