#!/usr/bin/env bash
# Bash script that accepts one argument run the whoami command under the user passed as an argument

user="$1"

if [ "$user" ] ; then
	chsh -s "$(command -v bash)" "$user" && su "$user" -c "whoami"
fi
