#!/usr/bin/env bash
# nginx must be listening on all active IPs on port 8080
pkill apache2
sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
chmod 0644 /etc/nginx/nginx.conf
su nginx -c "service nginx start"
